package org.evomaster.e2etests.spring.mcp.bb

/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll
import  org.junit.jupiter.api.BeforeAll
import  org.junit.jupiter.api.BeforeEach
import  org.junit.jupiter.api.Test
import  org.junit.jupiter.api.Timeout
import  org.junit.jupiter.api.Assertions.*
import  java.util.List
import  org.evomaster.test.utils.EMTestUtils.*
import  org.evomaster.client.java.controller.SutHandler
import  java.math.BigDecimal
import  java.math.BigInteger
import  org.hamcrest.Matchers.*
import  org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*
import  org.evomaster.client.java.controller.contentMatchers.StringMatcher.*
import  org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*




/**
*  This file was automatically generated by EvoMaster on 2026-06-30T20:07:12.180562-03:00\[America/Argentina/Buenos_Aires\]
*  
*  The generated test suite contains 4 tests
*  
*  Covered targets: 4
*  
*  Used time: 0h 1m 0s
*  
*  Needed budget for current results: 37%
*  
*  This file contains test cases that represent failed calls, but not indicative of faults.
*  
*/
internal class EvoMaster_others_Test {

    
    companion object {
        private val baseUrlOfSut = "http://localhost:3000/mcp"
        const val BASE_URL = "http://localhost:3000/mcp"
        var sessionId: String = ""
        
        fun callMcp(url: String, method: String, params: Map<String, Any?>): Map<String, Any?> {
            val mapper = com.fasterxml.jackson.databind.ObjectMapper()
            val requestId = System.currentTimeMillis()
            val bodyMap = mapOf("jsonrpc" to "2.0", "id" to requestId, "method" to method, "params" to params)
            val bodyBytes = mapper.writeValueAsBytes(bodyMap)
            val conn = java.net.URL(url).openConnection() as java.net.HttpURLConnection
            conn.requestMethod = "POST"
            conn.setRequestProperty("Content-Type", "application/json")
            conn.setRequestProperty("Accept", "application/json, text/event-stream")
            if (sessionId.isNotEmpty()) conn.setRequestProperty("Mcp-Session-Id", sessionId)
            conn.doOutput = true
            conn.outputStream.use { it.write(bodyBytes) }
            val response = conn.inputStream.bufferedReader().readText()
            @Suppress("UNCHECKED_CAST")
            val parsed = mapper.readValue(response, Map::class.java) as Map<String, Any?>
            check(parsed["error"] == null) { "JSON-RPC error: ${parsed["error"]}" }
            @Suppress("UNCHECKED_CAST")
            return parsed["result"] as? Map<String, Any?> ?: emptyMap()
        }
        
        @BeforeAll
        @JvmStatic
        fun initMcpSession() {
            val mapper = com.fasterxml.jackson.databind.ObjectMapper()
            val initBody = mapper.writeValueAsBytes(mapOf(
                "jsonrpc" to "2.0", "id" to 1, "method" to "initialize",
                "params" to mapOf(
                    "protocolVersion" to "2024-11-05",
                    "clientInfo" to mapOf("name" to "EvoMasterTest", "version" to "1.0"),
                    "capabilities" to emptyMap<String, Any>()
                )
            ))
            val conn = java.net.URL("http://localhost:3000/mcp").openConnection() as java.net.HttpURLConnection
            conn.requestMethod = "POST"
            conn.setRequestProperty("Content-Type", "application/json")
            conn.setRequestProperty("Accept", "application/json, text/event-stream")
            conn.doOutput = true
            conn.outputStream.use { it.write(initBody) }
            val sessionHeader = conn.getHeaderField("Mcp-Session-Id")
            if (sessionHeader != null) sessionId = sessionHeader
            
            // send notifications/initialized
            val notifBody = mapper.writeValueAsBytes(mapOf(
                "jsonrpc" to "2.0", "method" to "notifications/initialized", "params" to emptyMap<String, Any>()
            ))
            val conn2 = java.net.URL("http://localhost:3000/mcp").openConnection() as java.net.HttpURLConnection
            conn2.requestMethod = "POST"
            conn2.setRequestProperty("Content-Type", "application/json")
            conn2.setRequestProperty("Accept", "application/json, text/event-stream")
            if (sessionId.isNotEmpty()) conn2.setRequestProperty("Mcp-Session-Id", sessionId)
            conn2.doOutput = true
            conn2.outputStream.use { it.write(notifBody) }
            conn2.responseCode
        }
        
        
        @BeforeAll
        @JvmStatic
        fun initClass() {
        }
        
        
    }
    
    
    
    
    
    
    /**
    *  MCP test: resource:reservations://reservation/{uuid}
    */
    @Test @Timeout(60)
    fun test_0()  {
        val res_0 = callMcp(BASE_URL, "resources/read",
            mapOf("uri" to "reservations://reservation/Js"))
        // callMcp throws if JSON-RPC returned an error; reaching here means the call succeeded
        assertNotNull(res_0)
    }
    
    
    /**
    *  MCP test: tool:delete_reservation
    */
    @Test @Timeout(60)
    fun test_1()  {
        val res_0 = callMcp(BASE_URL, "tools/call",
            mapOf("name" to "delete_reservation", "arguments" to mapOf("uuid" to "jLS4r4XXUS3jSCc")))
        assertFalse(res_0["isError"] as? Boolean ?: false)
        assertNotNull(res_0["content"])
    }
    
    
    /**
    *  MCP test: tool:get_reservations_for_user
    */
    @Test @Timeout(60)
    fun test_2()  {
        val res_0 = callMcp(BASE_URL, "tools/call",
            mapOf("name" to "get_reservations_for_user", "arguments" to mapOf("username" to "MpyLqeaa4IvpUmqw")))
        assertFalse(res_0["isError"] as? Boolean ?: false)
        assertNotNull(res_0["content"])
    }
    
    
    /**
    *  MCP test: tool:get_all_reservations
    */
    @Test @Timeout(60)
    fun test_3()  {
        val res_0 = callMcp(BASE_URL, "tools/call",
            mapOf("name" to "get_all_reservations", "arguments" to emptyMap<String, Any?>()))
        assertFalse(res_0["isError"] as? Boolean ?: false)
        assertNotNull(res_0["content"])
    }


}
